# Generated by Django 2.2.7 on 2019-12-04 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='leads.Topic'),
        ),
    ]
