# Generated by Django 2.2.7 on 2019-12-04 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0007_topic_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='link',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
